### ISSUE TITLE
update for opayo endpoints

### ISSUE THREAD

**Issue by seanrockster** [umbraco/Umbraco.Commerce.PaymentProviders.Opayo#3]
Hi

Has the nuget package been updated for this recent change for the provider end points?

**Comment by seanrockster** [comment]
For v12

**Comment by umbracotrd** [comment]
Hi @seanrockster : the endpoints are updated in v10.1, 12.1 and 13.1 in **Umbraco Prereleases** feed. We're having a hard time getting an Opayo test account to verify the changes before release the update to nuget feed.

The details code changes are in this #2 . It will be wonderful if you take a look and confirm the endpoints.

If you're eager to see the plugin in action you can install the package from **Umbraco Prereleases** feed. The guide to install prerelease package can be found here: https://docs.umbraco.com/umbraco-cms/v/14.latest-beta/fundamentals/setup/install/preview-builds#prerelease-feed

**Comment by seanrockster** [comment]
Yes they are correct. We have a v12 site running so we are eager to get it updated.
