### ISSUE TITLE
How do I capture the opayo response data

### ISSUE THREAD

**Issue by seanrockster** [umbraco/Umbraco.Commerce.PaymentProviders.Opayo#4]
Hi

I've upgraded the nuget package to 12.1 now were getting failed orders but we cannot see how to get hold of the response data to determine why the transaction has failed.

**Comment by mattbrailsford** [comment]
the most recent update uprgaded the opayo endpoints as it was our understanding the old endpoints were being shut down. Is there a setting in your account that says which endpoints to use?

In terms of debugging, it might just be easiest to pull down the source code and compile it yourself to be able to attach a debugger.

**Comment by seanrockster** [comment]
Hi Matt

I'd assume they're running concurrently, otherwise it would be a monumental task to get everyone to switch on the same day :D. There is no account setting that we can see.

We are begin redirected to the failed url however we just don't how to get the response from opayo to figure out whats happened. I've looked through the available notifications but I cannot see anything obvious for grabbing the data.

I'll try your suggestion.

**Comment by mattbrailsford** [comment]
Yea, my worry was that maybe there was a toggle in peoples account we aren't aware of (honestly, we are working blind with Opayo as they won't give us a test account).

Let me know how you get on debugging.

**Comment by seanrockster** [comment]
Seems to be data related.
