### ISSUE TITLE
Request to publish PR #5 to nuget for 12.x

### ISSUE THREAD

**Issue by seanrockster** [umbraco/Umbraco.Commerce.PaymentProviders.Opayo#6]
Hi

Can you publish an updated nuget for 12.x ?

Thanks.

**Comment by umbracotrd** [comment]
@seanrockster : Sorry I don't get your point. Which update are you talking about?

**Comment by seanrockster** [comment]
Hi @umbracotrd we are using v12.1 of this plugin, however after the PR we'd like to have the additional logging feature. We are deploying via devops so its restoring the current version of the plugin. Thanks.

**Comment by umbracotrd** [comment]
@seanrockster : As I understand, you're wanting to have this PR (https://github.com/umbraco/Umbraco.Commerce.PaymentProviders.Opayo/pull/5/files) to be released on nuget. Is that correct?

**Comment by seanrockster** [comment]
Yes please

**Comment by umbracotrd** [comment]
@seanrockster : I've published #5 to nuget v12.1.1 (https://www.nuget.org/packages/Umbraco.Commerce.PaymentProviders.Opayo/12.1.1). It should be indexed and searchable in few minutes.
